# Generated by Django 5.0.3 on 2024-03-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.IntegerField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.car')),
            ],
        ),
    ]
