# Generated by Django 5.0.3 on 2024-03-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Not Accepted', 'Not Accepted'), ('Waiting', 'Waiting')], default='Waiting', max_length=12),
        ),
    ]
